In [1]:
import polars as pl
import plotly.express as px
from datetime import datetime

pl.Config.set_tbl_rows(30)

polars.config.Config

In [2]:
df_complete = pl.read_csv("raw_data/sample.csv")
df_complete.glimpse()
df_complete.columns

Rows: 582054
Columns: 29
$ PlateNumb         <str> '393-FL', '393-FL', '393-FL', '393-FL', '393-FL', '393-FL', '806-FZ', '806-FZ', '806-FZ', '806-FZ'
$ OperatorID        <i64> 35, 35, 35, 35, 35, 35, 35, 35, 35, 35
$ OperatorNo        <i64> 1308, 1308, 1308, 1308, 1308, 1308, 1308, 1308, 1308, 1308
$ RouteUID          <str> 'THB0968', 'THB0968', 'THB0968', 'THB0968', 'THB0968', 'THB0968', 'THB0968', 'THB0968', 'THB0968', 'THB0968'
$ RouteID           <i64> 968, 968, 968, 968, 968, 968, 968, 968, 968, 968
$ RouteNameZh_tw    <i64> 968, 968, 968, 968, 968, 968, 968, 968, 968, 968
$ RouteNameEn       <i64> 968, 968, 968, 968, 968, 968, 968, 968, 968, 968
$ SubRouteUID       <str> 'THB0968A2', 'THB0968A2', 'THB0968A2', 'THB0968A2', 'THB096801', 'THB0968A1', 'THB0968A1', 'THB0968A1', 'THB0968A2', 'THB0968A2'
$ SubRouteID        <str> '0968A2', '0968A2', '0968A2', '0968A2', '096801', '0968A1', '0968A1', '0968A1', '0968A2', '0968A2'
$ SubRouteNameZh_tw <str> '0968A', '0968A', '0968A', '0968A', '0968', '0968A', '0968A', '0968A', '0968A', '0968A'
$ SubRouteNameEn    <str> '0968A', '0968A', '0968A', '0968A', '0968', '0968A', '0968A', '0968A', '0968A', '0968A'
$ Direction         <str> '返程', '返程', '返程', '返程', '去程', '去程', '去程', '去程', '返程', '返程'
$ StopUID           <str> 'THB300178', 'THB300178', 'THB300182', 'THB300182', 'THB300194', 'THB300192', 'THB300194', 'THB300194', 'THB300182', 'THB300178'
$ StopID            <i64> 300178, 300178, 300182, 300182, 300194, 300192, 300194, 300194, 300182, 300178
$ StopNameZh_tw     <str> '大竹消防隊', '大竹消防隊', '大竹上興路口', '大竹上興路口', '光明國小', '南昌路口', '光明國小', '光明國小', '大竹上興路口', '大竹消防隊'
$ StopNameEn        <str> 'Dajhu Fire Brigade', 'Dajhu Fire Brigade', 'Dajhu & Shangsing Intersection', 'Dajhu & Shangsing Intersection', 'Guangming Elementary School', 'Nanchang Intersection', 'Guangming Elementary School', 'Guangming Elementary School', 'Dajhu & Shangsing Intersection', 'Dajhu Fire Brigade'
$ StopSequence      <i64> 10, 10, 9, 9, 8, 8, 9, 9, 9, 10
$ MessageType       <str> '非定期', '非定期', '非定期', '非定期', '非定期', '非定期', '非定期', '非定期', '非定期', '非定期'
$ DutyStatus        <str> '開始', '開始', '開始', '開始', '開始', '開始', '正常', '正常', '正常', '正常'
$ BusStatus         <str> '正常', '正常', '正常', '正常', '正常', '正常', '正常', '正常', '正常', '正常'
$ A2EventType       <str> '進站', '離站', '進站', '離站', '離站', '離站', '進站', '離站', '離站', '進站'
$ GPSTime           <str> '2026-02-25T15:18:09+08:00', '2026-02-25T15:18:50+08:00', '2026-02-25T15:17:45+08:00', '2026-02-25T15:17:57+08:00', '2026-02-25T07:22:43+08:00', '2026-02-25T10:11:26+08:00', '2026-02-25T14:24:15+08:00', '2026-02-25T14:24:54+08:00', '2026-02-25T09:43:12+08:00', '2026-02-25T09:43:59+08:00'
$ TripStartTimeType <str> '預估發車時間', '預估發車時間', '預估發車時間', '預估發車時間', '預估發車時間', '無法推估發車時間', '實際發車時間', '實際發車時間', '實際發車時間', '實際發車時間'
$ TripStartTime     <str> '2026-02-25T14:04:41+08:00', '2026-02-25T14:04:41+08:00', '2026-02-25T14:04:41+08:00', '2026-02-25T14:04:41+08:00', '2026-02-25T06:58:36+08:00', null, '2026-02-25T14:00:49+08:00', '2026-02-25T14:00:49+08:00', '2026-02-25T09:01:19+08:00', '2026-02-25T09:01:19+08:00'
$ TransTime         <str> null, null, null, null, null, null, null, null, null, null
$ SrcRecTime        <str> '2026-02-25T15:18:11+08:00', '2026-02-25T15:18:52+08:00', '2026-02-25T15:17:47+08:00', '2026-02-25T15:17:59+08:00', '2026-02-25T07:22:45+08:00', '2026-02-25T10:11:28+08:00', '2026-02-25T14:24:15+08:00', '2026-02-25T14:24:54+08:00', '2026-02-25T09:43:12+08:00', '2026-02-25T09:43:59+08:00'
$ SrcTransTime      <str> '2026-02-25T15:18:11+08:00', '2026-02-25T15:18:52+08:00', '2026-02-25T15:17:47+08:00', '2026-02-25T15:17:59+08:00', '2026-02-25T07:22:45+08:00', '2026-02-25T10:11:28+08:00', '2026-02-25T14:24:15+08:00', '2026-02-25T14:24:54+08:00', '2026-02-25T09:43:12+08:00', '2026-02-25T09:43:59+08:00'
$ SrcUpdateTime     <str> null, null, null, null, null, null, null, null, null, null
$ UpdateTime        <str> '2026-02-25T15:18:14+08:00', '2026-02-25T15:18:54+08:00', '2026-02-25T15:17:49+08:00', '2026-02-25T15:18:04+08:00', '2026-02-25T07:22:49+08:00', '2026-02-25T10:11:34+08:00', '2026-02-25T14:24:19+08:00', '2026-02-25T14:24:59+08:00', '2026-02-25T09:43:14+08:00', '2026-02-25T09:44:04+08:00'

['PlateNumb',
 'OperatorID',
 'OperatorNo',
 'RouteUID',
 'RouteID',
 'RouteNameZh_tw',
 'RouteNameEn',
 'SubRouteUID',
 'SubRouteID',
 'SubRouteNameZh_tw',
 'SubRouteNameEn',
 'Direction',
 'StopUID',
 'StopID',
 'StopNameZh_tw',
 'StopNameEn',
 'StopSequence',
 'MessageType',
 'DutyStatus',
 'BusStatus',
 'A2EventType',
 'GPSTime',
 'TripStartTimeType',
 'TripStartTime',
 'TransTime',
 'SrcRecTime',
 'SrcTransTime',
 'SrcUpdateTime',
 'UpdateTime']

In [3]:
df_complete.head()

shape: (5, 29)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ PlateNumb ┆ OperatorI ┆ OperatorN ┆ RouteUID ┆ … ┆ SrcRecTim ┆ SrcTransT ┆ SrcUpdate ┆ UpdateTim │
│ ---       ┆ D         ┆ o         ┆ ---      ┆   ┆ e         ┆ ime       ┆ Time      ┆ e         │
│ str       ┆ ---       ┆ ---       ┆ str      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│           ┆ i64       ┆ i64       ┆          ┆   ┆ str       ┆ str       ┆ str       ┆ str       │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 393-FL    ┆ 35        ┆ 1308      ┆ THB0968  ┆ … ┆ 2026-02-2 ┆ 2026-02-2 ┆ null      ┆ 2026-02-2 │
│           ┆           ┆           ┆          ┆   ┆ 5T15:18:1 ┆ 5T15:18:1 ┆           ┆ 5T15:18:1 │
│           ┆           ┆           ┆          ┆   ┆ 1+08:00   ┆ 1+08:00   ┆           ┆ 4+08:00   │
│ 393-FL    ┆ 35        ┆ 1308      ┆ THB0968  ┆ … ┆ 2026-02-2 ┆ 2026-02-2 ┆ null      ┆ 2026-02-2 │
│           ┆           ┆           ┆          ┆   ┆ 5T15:18:5 ┆ 5T15:18:5 ┆           ┆ 5T15:18:5 │
│           ┆           ┆           ┆          ┆   ┆ 2+08:00   ┆ 2+08:00   ┆           ┆ 4+08:00   │
│ 393-FL    ┆ 35        ┆ 1308      ┆ THB0968  ┆ … ┆ 2026-02-2 ┆ 2026-02-2 ┆ null      ┆ 2026-02-2 │
│           ┆           ┆           ┆          ┆   ┆ 5T15:17:4 ┆ 5T15:17:4 ┆           ┆ 5T15:17:4 │
│           ┆           ┆           ┆          ┆   ┆ 7+08:00   ┆ 7+08:00   ┆           ┆ 9+08:00   │
│ 393-FL    ┆ 35        ┆ 1308      ┆ THB0968  ┆ … ┆ 2026-02-2 ┆ 2026-02-2 ┆ null      ┆ 2026-02-2 │
│           ┆           ┆           ┆          ┆   ┆ 5T15:17:5 ┆ 5T15:17:5 ┆           ┆ 5T15:18:0 │
│           ┆           ┆           ┆          ┆   ┆ 9+08:00   ┆ 9+08:00   ┆           ┆ 4+08:00   │
│ 393-FL    ┆ 35        ┆ 1308      ┆ THB0968  ┆ … ┆ 2026-02-2 ┆ 2026-02-2 ┆ null      ┆ 2026-02-2 │
│           ┆           ┆           ┆          ┆   ┆ 5T07:22:4 ┆ 5T07:22:4 ┆           ┆ 5T07:22:4 │
│           ┆           ┆           ┆          ┆   ┆ 5+08:00   ┆ 5+08:00   ┆           ┆ 9+08:00   │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [12]:
# Prepare df of a specific route

TARGET_ROUTEID = 1728

df = (
    df_complete.filter(
        pl.col("RouteID") == TARGET_ROUTEID,
        pl.col("TripStartTimeType") == "實際發車時間",
    )
    .with_columns(
        pl.col("GPSTime")
        .str.replace(r"\+08:00", "")
        .str.to_datetime(format="%Y-%m-%dT%H:%M:%S")
        .alias("Time"),
    )
    .drop(
        [
            "GPSTime",
            "OperatorID",
            "OperatorNo",
            "RouteUID",
            "RouteID",
            "OperatorID",
            "OperatorNo",
            "RouteUID",
            "RouteID",
            "StopUID",
            "StopID",
            "TripStartTime",
            "TransTime",
            "SrcRecTime",
            "SrcTransTime",
            "SrcUpdateTime",
            "UpdateTime",
            "RouteNameZh_tw",
            "RouteNameEn",
            "SubRouteUID",
            "SubRouteID",
            "SubRouteNameZh_tw",
            "SubRouteNameEn",
            "StopNameEn",
            "StopSequence",
            "MessageType",
            "TripStartTimeType",
        ]
    )
)
df.glimpse()

Rows: 1795
Columns: 7
$ PlateNumb              <str> '057-FS', '057-FS', '057-FS', 'KKB-2059', '057-FS', 'KKB-2057', '057-FS', 'KKB-1713', 'KKB-2670', '057-FS'
$ Direction              <str> '返程', '返程', '返程', '返程', '返程', '去程', '返程', '去程', '返程', '去程'
$ StopNameZh_tw          <str> '幸安國小', '幸安國小', '仁愛建國路口一', '清華大學', '仁愛建國路口一', '捷運公館站', '捷運景美站', '龍潭運動公園', '科技生活館', '師大分部'
$ DutyStatus             <str> '開始', '開始', '開始', '開始', '開始', '開始', '開始', '開始', '開始', '開始'
$ BusStatus              <str> '正常', '正常', '正常', '正常', '正常', '正常', '正常', '正常', '正常', '正常'
$ A2EventType            <str> '離站', '進站', '進站', '進站', '離站', '進站', '離站', '離站', '離站', '離站'
$ Time          <datetime[μs]> 2026-02-25 16:15:27, 2026-02-25 16:15:14, 2026-02-25 16:15:32, 2026-02-25 16:15:38, 2026-02-25 16:15:50, 2026-02-25 16:15:59, 2026-02-25 21:21:14, 2026-02-25 21:21:34, 2026-02-25 21:21:02, 2026-02-25 11:22:13

In [41]:
fig = px.bar(
    df.filter(pl.col("Direction") == "去程")
    .group_by(["StopNameZh_tw", "A2EventType"])
    .len()
    .sort(["StopNameZh_tw", "A2EventType"]),
    y="StopNameZh_tw",
    x="len",
    color="A2EventType",
)
fig.show(renderer="browser")

In [14]:
df.head()

shape: (5, 7)
┌───────────┬───────────┬────────────────┬────────────┬───────────┬─────────────┬──────────────┐
│ PlateNumb ┆ Direction ┆ StopNameZh_tw  ┆ DutyStatus ┆ BusStatus ┆ A2EventType ┆ Time         │
│ ---       ┆ ---       ┆ ---            ┆ ---        ┆ ---       ┆ ---         ┆ ---          │
│ str       ┆ str       ┆ str            ┆ str        ┆ str       ┆ str         ┆ datetime[μs] │
╞═══════════╪═══════════╪════════════════╪════════════╪═══════════╪═════════════╪══════════════╡
│ 057-FS    ┆ 返程      ┆ 幸安國小       ┆ 開始       ┆ 正常      ┆ 離站        ┆ 2026-02-25   │
│           ┆           ┆                ┆            ┆           ┆             ┆ 16:15:27     │
│ 057-FS    ┆ 返程      ┆ 幸安國小       ┆ 開始       ┆ 正常      ┆ 進站        ┆ 2026-02-25   │
│           ┆           ┆                ┆            ┆           ┆             ┆ 16:15:14     │
│ 057-FS    ┆ 返程      ┆ 仁愛建國路口一 ┆ 開始       ┆ 正常      ┆ 進站        ┆ 2026-02-25   │
│           ┆           ┆                ┆            ┆           ┆             ┆ 16:15:32     │
│ KKB-2059  ┆ 返程      ┆ 清華大學       ┆ 開始       ┆ 正常      ┆ 進站        ┆ 2026-02-25   │
│           ┆           ┆                ┆            ┆           ┆             ┆ 16:15:38     │
│ 057-FS    ┆ 返程      ┆ 仁愛建國路口一 ┆ 開始       ┆ 正常      ┆ 離站        ┆ 2026-02-25   │
│           ┆           ┆                ┆            ┆           ┆             ┆ 16:15:50     │
└───────────┴───────────┴────────────────┴────────────┴───────────┴─────────────┴──────────────┘

In [36]:
df.filter(
    # pl.col("PlateNumb") == "KKB-2057",
    pl.col("A2EventType") == "進站",
    pl.col("StopNameZh_tw") == "清華大學",
    pl.col("Direction") == "返程",
).sort("Time")

shape: (22, 7)
┌───────────┬───────────┬───────────────┬────────────┬───────────┬─────────────┬──────────────┐
│ PlateNumb ┆ Direction ┆ StopNameZh_tw ┆ DutyStatus ┆ BusStatus ┆ A2EventType ┆ Time         │
│ ---       ┆ ---       ┆ ---           ┆ ---        ┆ ---       ┆ ---         ┆ ---          │
│ str       ┆ str       ┆ str           ┆ str        ┆ str       ┆ str         ┆ datetime[μs] │
╞═══════════╪═══════════╪═══════════════╪════════════╪═══════════╪═════════════╪══════════════╡
│ KKB-2058  ┆ 返程      ┆ 清華大學      ┆ 開始       ┆ 正常      ┆ 進站        ┆ 2026-02-25   │
│           ┆           ┆               ┆            ┆           ┆             ┆ 05:26:41     │
│ KKB-2669  ┆ 返程      ┆ 清華大學      ┆ 開始       ┆ 正常      ┆ 進站        ┆ 2026-02-25   │
│           ┆           ┆               ┆            ┆           ┆             ┆ 05:50:44     │
│ KKB-1715  ┆ 返程      ┆ 清華大學      ┆ 開始       ┆ 正常      ┆ 進站        ┆ 2026-02-25   │
│           ┆           ┆               ┆            ┆           ┆             ┆ 06:12:52     │
│ KKB-2057  ┆ 返程      ┆ 清華大學      ┆ 開始       ┆ 正常      ┆ 進站        ┆ 2026-02-25   │
│           ┆           ┆               ┆            ┆           ┆             ┆ 06:28:44     │
│ 057-FS    ┆ 返程      ┆ 清華大學      ┆ 開始       ┆ 正常      ┆ 進站        ┆ 2026-02-25   │
│           ┆           ┆               ┆            ┆           ┆             ┆ 06:54:42     │
│ KKB-2035  ┆ 返程      ┆ 清華大學      ┆ 開始       ┆ 正常      ┆ 進站        ┆ 2026-02-25   │
│           ┆           ┆               ┆            ┆           ┆             ┆ 07:13:13     │
│ KKB-2055  ┆ 返程      ┆ 清華大學      ┆ 開始       ┆ 正常      ┆ 進站        ┆ 2026-02-25   │
│           ┆           ┆               ┆            ┆           ┆             ┆ 08:16:58     │
│ KKB-2059  ┆ 返程      ┆ 清華大學      ┆ 開始       ┆ 正常      ┆ 進站        ┆ 2026-02-25   │
│           ┆           ┆               ┆            ┆           ┆             ┆ 09:10:49     │
│ KKB-2670  ┆ 返程      ┆ 清華大學      ┆ 開始       ┆ 正常      ┆ 進站        ┆ 2026-02-25   │
│           ┆           ┆               ┆            ┆           ┆             ┆ 10:15:11     │
│ KKB-1713  ┆ 返程      ┆ 清華大學      ┆ 開始       ┆ 正常      ┆ 進站        ┆ 2026-02-25   │
│           ┆           ┆               ┆            ┆           ┆             ┆ 11:11:21     │
│ KKB-1692  ┆ 返程      ┆ 清華大學      ┆ 開始       ┆ 正常      ┆ 進站        ┆ 2026-02-25   │
│           ┆           ┆               ┆            ┆           ┆             ┆ 12:13:59     │
│ KKB-2057  ┆ 返程      ┆ 清華大學      ┆ 開始       ┆ 正常      ┆ 進站        ┆ 2026-02-25   │
│           ┆           ┆               ┆            ┆           ┆             ┆ 13:10:22     │
│ 057-FS    ┆ 返程      ┆ 清華大學      ┆ 開始       ┆ 正常      ┆ 進站        ┆ 2026-02-25   │
│           ┆           ┆               ┆            ┆           ┆             ┆ 14:12:49     │
│ KKB-2669  ┆ 返程      ┆ 清華大學      ┆ 開始       ┆ 正常      ┆ 進站        ┆ 2026-02-25   │
│           ┆           ┆               ┆            ┆           ┆             ┆ 15:12:58     │
│ KKB-2059  ┆ 返程      ┆ 清華大學      ┆ 開始       ┆ 正常      ┆ 進站        ┆ 2026-02-25   │
│           ┆           ┆               ┆            ┆           ┆             ┆ 16:15:38     │
│ KKB-2035  ┆ 返程      ┆ 清華大學      ┆ 開始       ┆ 正常      ┆ 進站        ┆ 2026-02-25   │
│           ┆           ┆               ┆            ┆           ┆             ┆ 16:53:08     │
│ KKB-1713  ┆ 返程      ┆ 清華大學      ┆ 開始       ┆ 正常      ┆ 進站        ┆ 2026-02-25   │
│           ┆           ┆               ┆            ┆           ┆             ┆ 17:35:09     │
│ KKB-1692  ┆ 返程      ┆ 清華大學      ┆ 開始       ┆ 正常      ┆ 進站        ┆ 2026-02-25   │
│           ┆           ┆               ┆            ┆           ┆             ┆ 18:03:24     │
│ 057-FS    ┆ 返程      ┆ 清華大學      ┆ 開始       ┆ 正常      ┆ 進站        ┆ 2026-02-25   │
│           ┆           ┆               ┆            ┆           ┆             ┆ 19:37:36     │
│ KKB-2055  ┆ 返程      ┆ 清華大學      ┆ 開始       ┆ 正常      ┆ 進站        ┆ 2026-02-25   │
│           ┆           ┆               ┆            ┆           ┆             ┆ 20:12:32     │
│ KKB-2670  ┆ 返程      ┆ 清華大學      ┆ 開始       ┆ 正常      ┆ 進站        ┆ 2026-02-25   │
│           ┆           ┆               ┆            ┆           ┆             ┆ 21:13:34     │
│ KKB-2059  ┆ 返程      ┆ 清華大學      ┆ 開始       ┆ 正常      ┆ 進站        ┆ 2026-02-25   │
│           ┆           ┆               ┆            ┆           ┆             ┆ 22:12:58     │
└───────────┴───────────┴───────────────┴────────────┴───────────┴─────────────┴──────────────┘

In [43]:
depart = df.filter(
    # pl.col("PlateNumb") == "KKB-2057",
    pl.col("A2EventType") == "離站",
    pl.col("StopNameZh_tw") == "新竹轉運站",
    pl.col("Direction") == "返程",
).sort("Time")
depart

shape: (22, 7)
┌───────────┬───────────┬───────────────┬────────────┬───────────┬─────────────┬──────────────┐
│ PlateNumb ┆ Direction ┆ StopNameZh_tw ┆ DutyStatus ┆ BusStatus ┆ A2EventType ┆ Time         │
│ ---       ┆ ---       ┆ ---           ┆ ---        ┆ ---       ┆ ---         ┆ ---          │
│ str       ┆ str       ┆ str           ┆ str        ┆ str       ┆ str         ┆ datetime[μs] │
╞═══════════╪═══════════╪═══════════════╪════════════╪═══════════╪═════════════╪══════════════╡
│ KKB-2058  ┆ 返程      ┆ 新竹轉運站    ┆ 開始       ┆ 正常      ┆ 離站        ┆ 2026-02-25   │
│           ┆           ┆               ┆            ┆           ┆             ┆ 05:15:46     │
│ KKB-2669  ┆ 返程      ┆ 新竹轉運站    ┆ 開始       ┆ 正常      ┆ 離站        ┆ 2026-02-25   │
│           ┆           ┆               ┆            ┆           ┆             ┆ 05:40:54     │
│ KKB-1715  ┆ 返程      ┆ 新竹轉運站    ┆ 開始       ┆ 正常      ┆ 離站        ┆ 2026-02-25   │
│           ┆           ┆               ┆            ┆           ┆             ┆ 06:02:19     │
│ KKB-2057  ┆ 返程      ┆ 新竹轉運站    ┆ 開始       ┆ 正常      ┆ 離站        ┆ 2026-02-25   │
│           ┆           ┆               ┆            ┆           ┆             ┆ 06:20:04     │
│ 057-FS    ┆ 返程      ┆ 新竹轉運站    ┆ 開始       ┆ 正常      ┆ 離站        ┆ 2026-02-25   │
│           ┆           ┆               ┆            ┆           ┆             ┆ 06:42:05     │
│ KKB-2035  ┆ 返程      ┆ 新竹轉運站    ┆ 開始       ┆ 正常      ┆ 離站        ┆ 2026-02-25   │
│           ┆           ┆               ┆            ┆           ┆             ┆ 07:01:33     │
│ KKB-2055  ┆ 返程      ┆ 新竹轉運站    ┆ 開始       ┆ 正常      ┆ 離站        ┆ 2026-02-25   │
│           ┆           ┆               ┆            ┆           ┆             ┆ 08:01:17     │
│ KKB-2059  ┆ 返程      ┆ 新竹轉運站    ┆ 開始       ┆ 正常      ┆ 離站        ┆ 2026-02-25   │
│           ┆           ┆               ┆            ┆           ┆             ┆ 09:01:20     │
│ KKB-2670  ┆ 返程      ┆ 新竹轉運站    ┆ 開始       ┆ 正常      ┆ 離站        ┆ 2026-02-25   │
│           ┆           ┆               ┆            ┆           ┆             ┆ 10:03:37     │
│ KKB-1713  ┆ 返程      ┆ 新竹轉運站    ┆ 開始       ┆ 正常      ┆ 離站        ┆ 2026-02-25   │
│           ┆           ┆               ┆            ┆           ┆             ┆ 11:01:18     │
│ KKB-1692  ┆ 返程      ┆ 新竹轉運站    ┆ 開始       ┆ 正常      ┆ 離站        ┆ 2026-02-25   │
│           ┆           ┆               ┆            ┆           ┆             ┆ 12:01:34     │
│ KKB-2057  ┆ 返程      ┆ 新竹轉運站    ┆ 開始       ┆ 正常      ┆ 離站        ┆ 2026-02-25   │
│           ┆           ┆               ┆            ┆           ┆             ┆ 13:00:24     │
│ 057-FS    ┆ 返程      ┆ 新竹轉運站    ┆ 開始       ┆ 正常      ┆ 離站        ┆ 2026-02-25   │
│           ┆           ┆               ┆            ┆           ┆             ┆ 14:02:23     │
│ KKB-2669  ┆ 返程      ┆ 新竹轉運站    ┆ 開始       ┆ 正常      ┆ 離站        ┆ 2026-02-25   │
│           ┆           ┆               ┆            ┆           ┆             ┆ 15:00:47     │
│ KKB-2059  ┆ 返程      ┆ 新竹轉運站    ┆ 開始       ┆ 正常      ┆ 離站        ┆ 2026-02-25   │
│           ┆           ┆               ┆            ┆           ┆             ┆ 16:01:48     │
│ KKB-2035  ┆ 返程      ┆ 新竹轉運站    ┆ 開始       ┆ 正常      ┆ 離站        ┆ 2026-02-25   │
│           ┆           ┆               ┆            ┆           ┆             ┆ 16:41:46     │
│ KKB-1713  ┆ 返程      ┆ 新竹轉運站    ┆ 開始       ┆ 正常      ┆ 離站        ┆ 2026-02-25   │
│           ┆           ┆               ┆            ┆           ┆             ┆ 17:21:16     │
│ KKB-1692  ┆ 返程      ┆ 新竹轉運站    ┆ 開始       ┆ 正常      ┆ 離站        ┆ 2026-02-25   │
│           ┆           ┆               ┆            ┆           ┆             ┆ 17:51:43     │
│ 057-FS    ┆ 返程      ┆ 新竹轉運站    ┆ 開始       ┆ 正常      ┆ 離站        ┆ 2026-02-25   │
│           ┆           ┆               ┆            ┆           ┆             ┆ 19:22:56     │
│ KKB-2055  ┆ 返程      ┆ 新竹轉運站    ┆ 開始       ┆ 正常      ┆ 離站        ┆ 2026-02-25   │
│           ┆           ┆               ┆            ┆           ┆             ┆ 20:01:31     │
│ KKB-2670  ┆ 返程      ┆ 新竹轉運站    ┆ 開始       ┆ 正常      ┆ 離站        ┆ 2026-02-25   │
│           ┆           ┆               ┆            ┆           ┆             ┆ 21:03:00     │
│ KKB-2059  ┆ 返程      ┆ 新竹轉運站    ┆ 開始       ┆ 正常      ┆ 離站        ┆ 2026-02-25   │
│           ┆           ┆               ┆            ┆           ┆             ┆ 22:01:39     │
└───────────┴───────────┴───────────────┴────────────┴───────────┴─────────────┴──────────────┘

In [45]:
destination = df.filter(
    pl.col("A2EventType") == "進站",
    pl.col("StopNameZh_tw") == "龍潭運動公園",
    pl.col("Direction") == "返程",
).sort("Time")
destination

shape: (21, 7)
┌───────────┬───────────┬───────────────┬────────────┬───────────┬─────────────┬──────────────┐
│ PlateNumb ┆ Direction ┆ StopNameZh_tw ┆ DutyStatus ┆ BusStatus ┆ A2EventType ┆ Time         │
│ ---       ┆ ---       ┆ ---           ┆ ---        ┆ ---       ┆ ---         ┆ ---          │
│ str       ┆ str       ┆ str           ┆ str        ┆ str       ┆ str         ┆ datetime[μs] │
╞═══════════╪═══════════╪═══════════════╪════════════╪═══════════╪═════════════╪══════════════╡
│ KKB-2058  ┆ 返程      ┆ 龍潭運動公園  ┆ 開始       ┆ 正常      ┆ 進站        ┆ 2026-02-25   │
│           ┆           ┆               ┆            ┆           ┆             ┆ 06:00:09     │
│ KKB-2669  ┆ 返程      ┆ 龍潭運動公園  ┆ 開始       ┆ 正常      ┆ 進站        ┆ 2026-02-25   │
│           ┆           ┆               ┆            ┆           ┆             ┆ 06:23:58     │
│ KKB-1715  ┆ 返程      ┆ 龍潭運動公園  ┆ 開始       ┆ 正常      ┆ 進站        ┆ 2026-02-25   │
│           ┆           ┆               ┆            ┆           ┆             ┆ 06:49:51     │
│ KKB-2057  ┆ 返程      ┆ 龍潭運動公園  ┆ 開始       ┆ 正常      ┆ 進站        ┆ 2026-02-25   │
│           ┆           ┆               ┆            ┆           ┆             ┆ 07:02:17     │
│ 057-FS    ┆ 返程      ┆ 龍潭運動公園  ┆ 開始       ┆ 正常      ┆ 進站        ┆ 2026-02-25   │
│           ┆           ┆               ┆            ┆           ┆             ┆ 07:35:25     │
│ KKB-2035  ┆ 返程      ┆ 龍潭運動公園  ┆ 開始       ┆ 正常      ┆ 進站        ┆ 2026-02-25   │
│           ┆           ┆               ┆            ┆           ┆             ┆ 07:50:22     │
│ KKB-2055  ┆ 返程      ┆ 龍潭運動公園  ┆ 開始       ┆ 正常      ┆ 進站        ┆ 2026-02-25   │
│           ┆           ┆               ┆            ┆           ┆             ┆ 09:12:24     │
│ KKB-2059  ┆ 返程      ┆ 龍潭運動公園  ┆ 開始       ┆ 正常      ┆ 進站        ┆ 2026-02-25   │
│           ┆           ┆               ┆            ┆           ┆             ┆ 10:08:11     │
│ KKB-2670  ┆ 返程      ┆ 龍潭運動公園  ┆ 開始       ┆ 正常      ┆ 進站        ┆ 2026-02-25   │
│           ┆           ┆               ┆            ┆           ┆             ┆ 10:59:46     │
│ KKB-1713  ┆ 返程      ┆ 龍潭運動公園  ┆ 開始       ┆ 正常      ┆ 進站        ┆ 2026-02-25   │
│           ┆           ┆               ┆            ┆           ┆             ┆ 11:53:50     │
│ KKB-2057  ┆ 返程      ┆ 龍潭運動公園  ┆ 開始       ┆ 正常      ┆ 進站        ┆ 2026-02-25   │
│           ┆           ┆               ┆            ┆           ┆             ┆ 13:53:54     │
│ 057-FS    ┆ 返程      ┆ 龍潭運動公園  ┆ 開始       ┆ 正常      ┆ 進站        ┆ 2026-02-25   │
│           ┆           ┆               ┆            ┆           ┆             ┆ 15:03:57     │
│ KKB-2669  ┆ 返程      ┆ 龍潭運動公園  ┆ 開始       ┆ 正常      ┆ 進站        ┆ 2026-02-25   │
│           ┆           ┆               ┆            ┆           ┆             ┆ 16:00:15     │
│ KKB-2059  ┆ 返程      ┆ 龍潭運動公園  ┆ 開始       ┆ 正常      ┆ 進站        ┆ 2026-02-25   │
│           ┆           ┆               ┆            ┆           ┆             ┆ 17:07:09     │
│ KKB-2035  ┆ 返程      ┆ 龍潭運動公園  ┆ 開始       ┆ 正常      ┆ 進站        ┆ 2026-02-25   │
│           ┆           ┆               ┆            ┆           ┆             ┆ 17:44:58     │
│ KKB-1713  ┆ 返程      ┆ 龍潭運動公園  ┆ 開始       ┆ 正常      ┆ 進站        ┆ 2026-02-25   │
│           ┆           ┆               ┆            ┆           ┆             ┆ 18:30:34     │
│ KKB-1692  ┆ 返程      ┆ 龍潭運動公園  ┆ 開始       ┆ 正常      ┆ 進站        ┆ 2026-02-25   │
│           ┆           ┆               ┆            ┆           ┆             ┆ 19:04:33     │
│ 057-FS    ┆ 返程      ┆ 龍潭運動公園  ┆ 開始       ┆ 正常      ┆ 進站        ┆ 2026-02-25   │
│           ┆           ┆               ┆            ┆           ┆             ┆ 20:32:19     │
│ KKB-2055  ┆ 返程      ┆ 龍潭運動公園  ┆ 開始       ┆ 正常      ┆ 進站        ┆ 2026-02-25   │
│           ┆           ┆               ┆            ┆           ┆             ┆ 21:00:24     │
│ KKB-2670  ┆ 返程      ┆ 龍潭運動公園  ┆ 開始       ┆ 正常      ┆ 進站        ┆ 2026-02-25   │
│           ┆           ┆               ┆            ┆           ┆             ┆ 21:51:54     │
│ KKB-2059  ┆ 返程      ┆ 龍潭運動公園  ┆ 開始       ┆ 正常      ┆ 進站        ┆ 2026-02-25   │
│           ┆           ┆               ┆            ┆           ┆             ┆ 23:06:27     │
└───────────┴───────────┴───────────────┴────────────┴───────────┴─────────────┴──────────────┘

In [52]:
result = depart.join_asof(
    destination,
    on="Time",
    by="PlateNumb",
    strategy="forward",  # Looks for the next available time in df_2
    check_sortedness=False,
)
result

shape: (22, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ PlateNumb ┆ Direction ┆ StopNameZ ┆ DutyStatu ┆ … ┆ StopNameZ ┆ DutyStatu ┆ BusStatus ┆ A2EventT │
│ ---       ┆ ---       ┆ h_tw      ┆ s         ┆   ┆ h_tw_righ ┆ s_right   ┆ _right    ┆ ype_righ │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ t         ┆ ---       ┆ ---       ┆ t        │
│           ┆           ┆ str       ┆ str       ┆   ┆ ---       ┆ str       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ str       ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ KKB-2058  ┆ 返程      ┆ 新竹轉運  ┆ 開始      ┆ … ┆ 龍潭運動  ┆ 開始      ┆ 正常      ┆ 進站     │
│           ┆           ┆ 站        ┆           ┆   ┆ 公園      ┆           ┆           ┆          │
│ KKB-2669  ┆ 返程      ┆ 新竹轉運  ┆ 開始      ┆ … ┆ 龍潭運動  ┆ 開始      ┆ 正常      ┆ 進站     │
│           ┆           ┆ 站        ┆           ┆   ┆ 公園      ┆           ┆           ┆          │
│ KKB-1715  ┆ 返程      ┆ 新竹轉運  ┆ 開始      ┆ … ┆ 龍潭運動  ┆ 開始      ┆ 正常      ┆ 進站     │
│           ┆           ┆ 站        ┆           ┆   ┆ 公園      ┆           ┆           ┆          │
│ KKB-2057  ┆ 返程      ┆ 新竹轉運  ┆ 開始      ┆ … ┆ 龍潭運動  ┆ 開始      ┆ 正常      ┆ 進站     │
│           ┆           ┆ 站        ┆           ┆   ┆ 公園      ┆           ┆           ┆          │
│ 057-FS    ┆ 返程      ┆ 新竹轉運  ┆ 開始      ┆ … ┆ 龍潭運動  ┆ 開始      ┆ 正常      ┆ 進站     │
│           ┆           ┆ 站        ┆           ┆   ┆ 公園      ┆           ┆           ┆          │
│ KKB-2035  ┆ 返程      ┆ 新竹轉運  ┆ 開始      ┆ … ┆ 龍潭運動  ┆ 開始      ┆ 正常      ┆ 進站     │
│           ┆           ┆ 站        ┆           ┆   ┆ 公園      ┆           ┆           ┆          │
│ KKB-2055  ┆ 返程      ┆ 新竹轉運  ┆ 開始      ┆ … ┆ 龍潭運動  ┆ 開始      ┆ 正常      ┆ 進站     │
│           ┆           ┆ 站        ┆           ┆   ┆ 公園      ┆           ┆           ┆          │
│ KKB-2059  ┆ 返程      ┆ 新竹轉運  ┆ 開始      ┆ … ┆ 龍潭運動  ┆ 開始      ┆ 正常      ┆ 進站     │
│           ┆           ┆ 站        ┆           ┆   ┆ 公園      ┆           ┆           ┆          │
│ KKB-2670  ┆ 返程      ┆ 新竹轉運  ┆ 開始      ┆ … ┆ 龍潭運動  ┆ 開始      ┆ 正常      ┆ 進站     │
│           ┆           ┆ 站        ┆           ┆   ┆ 公園      ┆           ┆           ┆          │
│ KKB-1713  ┆ 返程      ┆ 新竹轉運  ┆ 開始      ┆ … ┆ 龍潭運動  ┆ 開始      ┆ 正常      ┆ 進站     │
│           ┆           ┆ 站        ┆           ┆   ┆ 公園      ┆           ┆           ┆          │
│ KKB-1692  ┆ 返程      ┆ 新竹轉運  ┆ 開始      ┆ … ┆ 龍潭運動  ┆ 開始      ┆ 正常      ┆ 進站     │
│           ┆           ┆ 站        ┆           ┆   ┆ 公園      ┆           ┆           ┆          │
│ KKB-2057  ┆ 返程      ┆ 新竹轉運  ┆ 開始      ┆ … ┆ 龍潭運動  ┆ 開始      ┆ 正常      ┆ 進站     │
│           ┆           ┆ 站        ┆           ┆   ┆ 公園      ┆           ┆           ┆          │
│ 057-FS    ┆ 返程      ┆ 新竹轉運  ┆ 開始      ┆ … ┆ 龍潭運動  ┆ 開始      ┆ 正常      ┆ 進站     │
│           ┆           ┆ 站        ┆           ┆   ┆ 公園      ┆           ┆           ┆          │
│ KKB-2669  ┆ 返程      ┆ 新竹轉運  ┆ 開始      ┆ … ┆ 龍潭運動  ┆ 開始      ┆ 正常      ┆ 進站     │
│           ┆           ┆ 站        ┆           ┆   ┆ 公園      ┆           ┆           ┆          │
│ KKB-2059  ┆ 返程      ┆ 新竹轉運  ┆ 開始      ┆ … ┆ 龍潭運動  ┆ 開始      ┆ 正常      ┆ 進站     │
│           ┆           ┆ 站        ┆           ┆   ┆ 公園      ┆           ┆           ┆          │
│ KKB-2035  ┆ 返程      ┆ 新竹轉運  ┆ 開始      ┆ … ┆ 龍潭運動  ┆ 開始      ┆ 正常      ┆ 進站     │
│           ┆           ┆ 站        ┆           ┆   ┆ 公園      ┆           ┆           ┆          │
│ KKB-1713  ┆ 返程      ┆ 新竹轉運  ┆ 開始      ┆ … ┆ 龍潭運動  ┆ 開始      ┆ 正常      ┆ 進站     │
│           ┆           ┆ 站        ┆           ┆   ┆ 公園      ┆           ┆           ┆          │
│ KKB-1692  ┆ 返程      ┆ 新竹轉運  ┆ 開始      ┆ … ┆ 龍潭運動  ┆ 開始      ┆ 正常      ┆ 進站     │
│           ┆           ┆ 站        ┆           ┆   ┆ 公園      ┆           ┆           ┆          │
│ 057-FS    ┆ 返程      ┆ 新竹轉運  ┆ 開始      ┆ … ┆ 龍潭運動  ┆ 開始      ┆ 正常      ┆ 進站     │
│           ┆           ┆ 站        ┆           ┆   ┆ 公園      ┆           ┆           ┆          │
│ KKB-2055  ┆ 返程      ┆ 新竹轉運  ┆ 開始      ┆ … ┆ 龍潭運動  ┆ 開始      ┆ 正常      ┆ 進站     │
│           ┆           ┆ 站        ┆           ┆   ┆ 公園      ┆           ┆           ┆          │
│ KKB-2670  ┆ 返程      ┆ 新竹轉運  ┆ 開始      ┆ … ┆ 龍潭運動  ┆ 開始      ┆ 正常      ┆ 進站     │
│           ┆           ┆ 站        ┆           ┆   ┆ 公園      ┆           ┆           ┆          │
│ KKB-2059  ┆ 返程      ┆ 新竹轉運  ┆ 開始      ┆ … ┆ 龍潭運動  ┆ 開始      ┆ 正常      ┆ 進站     │
│           ┆           ┆ 站        ┆           ┆   ┆ 公園      ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [23]:
pl.DataFrame({"Start_time": first_time, "duration": second_time - first_time})

shape: (22, 2)
┌─────────────────────┬──────────────┐
│ Start_time          ┆ duration     │
│ ---                 ┆ ---          │
│ datetime[μs]        ┆ duration[μs] │
╞═════════════════════╪══════════════╡
│ 2026-02-25 05:15:46 ┆ 10m 55s      │
│ 2026-02-25 05:40:54 ┆ 9m 50s       │
│ 2026-02-25 06:02:19 ┆ 10m 33s      │
│ 2026-02-25 06:20:04 ┆ 8m 40s       │
│ 2026-02-25 06:42:05 ┆ 12m 37s      │
│ 2026-02-25 07:01:33 ┆ 11m 40s      │
│ 2026-02-25 08:01:17 ┆ 15m 41s      │
│ 2026-02-25 09:01:20 ┆ 9m 29s       │
│ 2026-02-25 10:03:37 ┆ 11m 34s      │
│ 2026-02-25 11:01:18 ┆ 10m 3s       │
│ 2026-02-25 12:01:34 ┆ 12m 25s      │
│ 2026-02-25 13:00:24 ┆ 9m 58s       │
│ 2026-02-25 14:02:23 ┆ 10m 26s      │
│ 2026-02-25 15:00:47 ┆ 12m 11s      │
│ 2026-02-25 16:01:48 ┆ 13m 50s      │
│ 2026-02-25 16:41:46 ┆ 11m 22s      │
│ 2026-02-25 17:21:16 ┆ 13m 53s      │
│ 2026-02-25 17:51:43 ┆ 11m 41s      │
│ 2026-02-25 19:22:56 ┆ 14m 40s      │
│ 2026-02-25 20:01:31 ┆ 11m 1s       │
│ 2026-02-25 21:03:00 ┆ 10m 34s      │
│ 2026-02-25 22:01:39 ┆ 11m 19s      │
└─────────────────────┴──────────────┘